# Generated by Django 5.1 on 2024-09-10 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettingsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('smtp_server', models.CharField(max_length=150)),
                ('smtp_port', models.IntegerField()),
                ('smtp_username', models.CharField(max_length=150)),
                ('smtp_password', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Paramètre appli',
                'verbose_name_plural': 'Paramètre applis',
            },
        ),
        migrations.CreateModel(
            name='SchoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('url_logo', models.URLField()),
                ('app', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school_app_id', to='school.appsettingsmodel')),
            ],
            options={
                'verbose_name': 'Ecole',
                'verbose_name_plural': 'Ecoles',
            },
        ),
    ]
